// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int Howmanytimetorun = Integer.parseInt(args[0]);
		int morethemhalf= 0;
		int lessorequal = 0;
		double Ratio;
		for (int i= 0 ; i < Howmanytimetorun ; i++)
		{
			double random = Math.random();
			if (random > 0.5)
			{
				morethemhalf = morethemhalf + 1;
			}
			else
			{
				lessorequal = lessorequal + 1;
			}
		}
		if (morethemhalf > lessorequal)
		{
			if (lessorequal == 0)
			{
				System.out.println("> 0.5: " + morethemhalf);
				System.out.println("<= 0.5: " + lessorequal);

			}
			else
			{
			Ratio = (double) lessorequal / morethemhalf;
			System.out.println("> 0.5: " + morethemhalf);
			System.out.println("<= 0.5: " + lessorequal);
			System.out.println("Ratio: " + Ratio ) ;
			}
		
		}
		else 
		{
			if (morethemhalf <= lessorequal)
			{
				if (morethemhalf == 0)
				{
					
				System.out.println("> 0.5: " + morethemhalf);
				System.out.println("<= 0.5: " + lessorequal);
				}
				else
				{
				Ratio =(double) morethemhalf / lessorequal;
				System.out.println("> 0.5: " + morethemhalf);
				System.out.println("<= 0.5: " + lessorequal);
				System.out.println("Ratio: " + Ratio ) ;
				}
			}


		}


	}
}
